var annotated =
[
    [ "biaxe", "namespacebiaxe.html", null ],
    [ "conditions", "namespaceconditions.html", "namespaceconditions" ],
    [ "correl_advanced", "namespacecorrel__advanced.html", null ],
    [ "correl_simple", "namespacecorrel__simple.html", null ],
    [ "crappy", "namespacecrappy.html", "namespacecrappy" ],
    [ "displayer", "namespacedisplayer.html", null ],
    [ "example", "namespaceexample.html", null ],
    [ "genraception", "namespacegenraception.html", null ],
    [ "interfaceCMdrive", "namespaceinterfaceCMdrive.html", "namespaceinterfaceCMdrive" ],
    [ "module_lister", "namespacemodule__lister.html", null ],
    [ "multiplex", "namespacemultiplex.html", null ],
    [ "oriental", "namespaceoriental.html", null ],
    [ "protection", "namespaceprotection.html", null ],
    [ "protection_par_axe", "namespaceprotection__par__axe.html", null ],
    [ "read", "namespaceread.html", null ],
    [ "read_write", "namespaceread__write.html", null ],
    [ "read_write2", "namespaceread__write2.html", null ],
    [ "save", "namespacesave.html", null ],
    [ "setup", "namespacesetup.html", null ],
    [ "test_gen", "namespacetest__gen.html", null ],
    [ "test_gui", "namespacetest__gui.html", "namespacetest__gui" ],
    [ "video_extenso_auto_drive", "namespacevideo__extenso__auto__drive.html", null ],
    [ "video_extenso_only", "namespacevideo__extenso__only.html", null ],
    [ "CaptureCAM_CL", "classCaptureCAM__CL.html", "classCaptureCAM__CL" ],
    [ "CaptureCAM_XIMEA", "classCaptureCAM__XIMEA.html", "classCaptureCAM__XIMEA" ],
    [ "Hello", "structHello.html", "structHello" ],
    [ "pyFgen", "structpyFgen.html", "structpyFgen" ],
    [ "VideoCapture", "structVideoCapture.html", "structVideoCapture" ]
];