var dir_03680f297d755c096b0a1ead13ee12b7 =
[
    [ "acq-crappy.py", "acq-crappy_8py.html", "acq-crappy_8py" ],
    [ "biaxe.py", "Examples_2biaxe_8py.html", "Examples_2biaxe_8py" ],
    [ "biotens.py", "Examples_2biotens_8py.html", "Examples_2biotens_8py" ],
    [ "conditions.py", "conditions_8py.html", "conditions_8py" ],
    [ "correl_advanced.py", "correl__advanced_8py.html", "correl__advanced_8py" ],
    [ "correl_simple.py", "correl__simple_8py.html", "correl__simple_8py" ],
    [ "dio_daqmx.py", "dio__daqmx_8py.html", "dio__daqmx_8py" ],
    [ "displayer.py", "Examples_2displayer_8py.html", "Examples_2displayer_8py" ],
    [ "drawing.py", "Examples_2drawing_8py.html", "Examples_2drawing_8py" ],
    [ "four.py", "four_8py.html", "four_8py" ],
    [ "four_test.py", "four__test_8py.html", "four__test_8py" ],
    [ "io_daqmx.py", "io__daqmx_8py.html", "io__daqmx_8py" ],
    [ "kollmorgen.py", "Examples_2kollmorgen_8py.html", "Examples_2kollmorgen_8py" ],
    [ "mean.py", "Examples_2mean_8py.html", "Examples_2mean_8py" ],
    [ "measure-crappy.py", "measure-crappy_8py.html", "measure-crappy_8py" ],
    [ "oldmeasure-crappy.py", "oldmeasure-crappy_8py.html", "oldmeasure-crappy_8py" ],
    [ "pid.py", "Examples_2pid_8py.html", "Examples_2pid_8py" ],
    [ "protection.py", "Examples_2protection_8py.html", "Examples_2protection_8py" ],
    [ "protection_par_axe.py", "protection__par__axe_8py.html", "protection__par__axe_8py" ],
    [ "read.py", "read_8py.html", "read_8py" ],
    [ "rw_comedi.py", "rw__comedi_8py.html", "rw__comedi_8py" ],
    [ "rw_labjack.py", "rw__labjack_8py.html", "rw__labjack_8py" ],
    [ "self-heating.py", "self-heating_8py.html", "self-heating_8py" ],
    [ "sim_four.py", "sim__four_8py.html", "sim__four_8py" ],
    [ "spectrum.py", "Examples_2spectrum_8py.html", "Examples_2spectrum_8py" ],
    [ "stream_t7.py", "stream__t7_8py.html", "stream__t7_8py" ],
    [ "thermocouple_daqmx.py", "thermocouple__daqmx_8py.html", "thermocouple__daqmx_8py" ],
    [ "thermocouple_t7.py", "thermocouple__t7_8py.html", "thermocouple__t7_8py" ],
    [ "video_extenso_auto_drive.py", "video__extenso__auto__drive_8py.html", "video__extenso__auto__drive_8py" ],
    [ "video_extenso_full.py", "video__extenso__full_8py.html", "video__extenso__full_8py" ],
    [ "video_extenso_only.py", "video__extenso__only_8py.html", "video__extenso__only_8py" ]
];