var namespaces =
[
    [ "biaxe", "namespacebiaxe.html", null ],
    [ "biotens", "namespacebiotens.html", null ],
    [ "conditions", "namespaceconditions.html", null ],
    [ "correl_advanced", "namespacecorrel__advanced.html", null ],
    [ "correl_simple", "namespacecorrel__simple.html", null ],
    [ "crappy", "namespacecrappy.html", "namespacecrappy" ],
    [ "displayer", "namespacedisplayer.html", null ],
    [ "drawing", "namespacedrawing.html", null ],
    [ "example", "namespaceexample.html", null ],
    [ "interfaceCMdrive", "namespaceinterfaceCMdrive.html", null ],
    [ "kollmorgen", "namespacekollmorgen.html", null ],
    [ "module_lister", "namespacemodule__lister.html", null ],
    [ "open_hdf", "namespaceopen__hdf.html", null ],
    [ "oriental", "namespaceoriental.html", null ],
    [ "pid", "namespacepid.html", null ],
    [ "pid_autotune", "namespacepid__autotune.html", null ],
    [ "protection", "namespaceprotection.html", null ],
    [ "protection_par_axe", "namespaceprotection__par__axe.html", null ],
    [ "read", "namespaceread.html", null ],
    [ "rw_comedi", "namespacerw__comedi.html", null ],
    [ "rw_labjack", "namespacerw__labjack.html", null ],
    [ "self-heating", "namespaceself-heating.html", null ],
    [ "setup", "namespacesetup.html", null ],
    [ "spectrum", "namespacespectrum.html", null ],
    [ "stream_t7", "namespacestream__t7.html", null ],
    [ "video_extenso_auto_drive", "namespacevideo__extenso__auto__drive.html", null ],
    [ "video_extenso_full", "namespacevideo__extenso__full.html", null ],
    [ "video_extenso_only", "namespacevideo__extenso__only.html", null ]
];